Implemented code to search product through barcode scanner
hotwax/inventorycount pull request #23
Opened 2021-11-09 10:24 UTC by azkyakhan

2021-11-10 13:26 UTC, dt2patel commented
Reviewed on my end for UI work. @adityasharma7 please take look at your end

2021-11-10 14:12 UTC, adityasharma7 requested changes

2021-11-10 14:12 UTC, adityasharma7 commented on src/views/Search.vue
> +        BarcodeScanner.startScan({ targetedFormats: ['UPC_A'] })
```suggestion
        BarcodeScanner.startScan({ targetedFormats: [ SupportedFormat.UPC_A] })
```
Use SupportedFormat enum instead
https://github.com/capacitor-community/barcode-scanner#target-only-specific-barcodes
https://github.com/capacitor-community/barcode-scanner/blob/main/src/definitions.ts#L18

2021-11-10 14:12 UTC, adityasharma7 commented on src/views/Search.vue
> +      const result = await BarcodeScanner.startScan(); // start scanning and wait for a result
We have prepare(), hideBackground() &, showBackground() method available
https://github.com/capacitor-community/barcode-scanner#preparing-a-scan
I think If we use them, we may be able to avoid the `scannerActive` flag

2021-11-10 14:12 UTC, adityasharma7 commented on src/views/Settings.vue
> +          <ion-select interface="popover" :placeholder="$t('store name')" :selected-text="currentFacility.name" @ionChange="setFacility($event)">
I think we should use `:value` instead of `:selected-text`
https://ionicframework.com/docs/api/select#properties

2021-11-10 14:12 UTC, adityasharma7 commented on src/views/Search.vue
> +        this.presentAlertConfirm(translate('No permission'), translate('Please allow camera access in your settings'));
We are translating twice, here and in method

2021-11-10 14:12 UTC, adityasharma7 commented on src/views/Search.vue
> +        this.presentAlertConfirm(translate('Error'), translate('Unable to start camera, please try again'));
We are translating twice, here and in method

2021-11-10 14:12 UTC, adityasharma7 commented on src/store/modules/product/actions.ts
> +    const upc = payload.product ? payload.product.upc : payload.upc;
I think we should handle based upon upc or sku in payload

2022-01-21 12:13 UTC, adityasharma7 commented
Done with https://github.com/hotwax/inventorycount/pull/43. Closing

2022-01-21 12:13 UTC, closed without merging